# Generated by Django 4.2 on 2023-08-06 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeMaverick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=24)),
                ('rank', models.IntegerField(default=0, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='get_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('ques_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('sol_id', models.IntegerField(default=0)),
                ('sol', models.TextField()),
                ('likes', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_id', models.IntegerField(default=0)),
                ('ques', models.TextField()),
                ('category', models.TextField()),
                ('src', models.TextField()),
                ('sols', models.ManyToManyField(related_name='get_solutions', to='CodeMaverick.solution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=64)),
                ('message', models.TextField(max_length=512)),
                ('status', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('room_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('messages', models.ManyToManyField(related_name='get_messages', to='CodeMaverick.message')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_chatroom_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_chatroom_messages', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CodeMaverick.team')),
            ],
        ),
    ]
