# Generated by Django 4.2.3 on 2023-07-18 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CodeMaverick", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
